server:
  port: 8008
spring:
  datasource:
    username: root
    password: testtest
    url: jdbc:mysql://localhost:3306/chat?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create # create-drop, create, update
    show-sql: false
